# Generated by Django 5.2 on 2025-05-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_link_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
    ]
